local key = vim.keymap

key.set("n", "[a<leader>", "1k")
key.set("n", "[r<leader>", "2k")
key.set("n", "[s<leader>", "3k")
key.set("n", "[t<leader>", "4k")
key.set("n", "[d<leader>", "5k")
key.set("n", "[h<leader>", "6k")
key.set("n", "[n<leader>", "7k")
key.set("n", "[e<leader>", "8k")
key.set("n", "[i<leader>", "9k")

key.set("n", "[ao", "10k")
key.set("n", "[aa", "11k")
key.set("n", "[ar", "12k")
key.set("n", "[as", "13k")
key.set("n", "[at", "14k")
key.set("n", "[ad", "15k")
key.set("n", "[ah", "16k")
key.set("n", "[an", "17k")
key.set("n", "[ae", "18k")
key.set("n", "[ai", "19k")

key.set("n", "[ro", "20k")
key.set("n", "[ra", "21k")
key.set("n", "[rr", "22k")
key.set("n", "[rs", "23k")
key.set("n", "[rt", "24k")
key.set("n", "[rd", "25k")
key.set("n", "[rh", "26k")
key.set("n", "[rn", "27k")
key.set("n", "[re", "28k")
key.set("n", "[ri", "29k")

key.set("n", "[so", "30k")
key.set("n", "[sa", "31k")
key.set("n", "[sr", "32k")
key.set("n", "[ss", "33k")
key.set("n", "[st", "34k")
key.set("n", "[sd", "35k")
key.set("n", "[sh", "36k")
key.set("n", "[sn", "37k")
key.set("n", "[se", "38k")
key.set("n", "[si", "39k")

key.set("n", "[to", "40k")
key.set("n", "[ta", "41k")
key.set("n", "[tr", "42k")
key.set("n", "[ts", "43k")
key.set("n", "[tt", "44k")
key.set("n", "[td", "45k")
key.set("n", "[th", "46k")
key.set("n", "[tn", "47k")
key.set("n", "[te", "48k")
key.set("n", "[ti", "49k")

key.set("n", "[do", "50k")
key.set("n", "[da", "51k")
key.set("n", "[dr", "52k")
key.set("n", "[ds", "53k")
key.set("n", "[dt", "54k")
key.set("n", "[dd", "55k")
key.set("n", "[dh", "56k")
key.set("n", "[dn", "57k")
key.set("n", "[de", "58k")
key.set("n", "[di", "59k")

key.set("n", "[ho", "60k")
key.set("n", "[ha", "61k")
key.set("n", "[hr", "62k")
key.set("n", "[hs", "63k")
key.set("n", "[ht", "64k")
key.set("n", "[hd", "65k")
key.set("n", "[hh", "66k")
key.set("n", "[hn", "67k")
key.set("n", "[he", "68k")
key.set("n", "[hi", "69k")

key.set("n", "[no", "70k")
key.set("n", "[na", "71k")
key.set("n", "[nr", "72k")
key.set("n", "[ns", "73k")
key.set("n", "[nt", "74k")
key.set("n", "[nd", "75k")
key.set("n", "[nh", "76k")
key.set("n", "[nn", "77k")
key.set("n", "[ne", "78k")
key.set("n", "[ni", "79k")

key.set("n", "[eo", "80k")
key.set("n", "[ea", "81k")
key.set("n", "[er", "82k")
key.set("n", "[es", "83k")
key.set("n", "[et", "84k")
key.set("n", "[ed", "85k")
key.set("n", "[eh", "86k")
key.set("n", "[en", "87k")
key.set("n", "[ee", "88k")
key.set("n", "[ei", "89k")

key.set("n", "[io", "90k")
key.set("n", "[ia", "91k")
key.set("n", "[ir", "92k")
key.set("n", "[is", "93k")
key.set("n", "[it", "94k")
key.set("n", "[id", "95k")
key.set("n", "[ih", "96k")
key.set("n", "[in", "97k")
key.set("n", "[ie", "98k")
key.set("n", "[ii", "99k")



key.set("n", "'a<leader>", "1j")
key.set("n", "'r<leader>", "2j")
key.set("n", "'s<leader>", "3j")
key.set("n", "'t<leader>", "4j")
key.set("n", "'d<leader>", "5j")
key.set("n", "'h<leader>", "6j")
key.set("n", "'n<leader>", "7j")
key.set("n", "'e<leader>", "8j")
key.set("n", "'i<leader>", "9j")

key.set("n", "'ao", "10j")
key.set("n", "'aa", "11j")
key.set("n", "'ar", "12j")
key.set("n", "'as", "13j")
key.set("n", "'at", "14j")
key.set("n", "'ad", "15j")
key.set("n", "'ah", "16j")
key.set("n", "'an", "17j")
key.set("n", "'ae", "18j")
key.set("n", "'ai", "19j")

key.set("n", "'ro", "20j")
key.set("n", "'ra", "21j")
key.set("n", "'rr", "22j")
key.set("n", "'rs", "23j")
key.set("n", "'rt", "24j")
key.set("n", "'rd", "25j")
key.set("n", "'rh", "26j")
key.set("n", "'rn", "27j")
key.set("n", "'re", "28j")
key.set("n", "'ri", "29j")

key.set("n", "'so", "30j")
key.set("n", "'sa", "31j")
key.set("n", "'sr", "32j")
key.set("n", "'ss", "33j")
key.set("n", "'st", "34j")
key.set("n", "'sd", "35j")
key.set("n", "'sh", "36j")
key.set("n", "'sn", "37j")
key.set("n", "'se", "38j")
key.set("n", "'si", "39j")

key.set("n", "'to", "40j")
key.set("n", "'ta", "41j")
key.set("n", "'tr", "42j")
key.set("n", "'ts", "43j")
key.set("n", "'tt", "44j")
key.set("n", "'td", "45j")
key.set("n", "'th", "46j")
key.set("n", "'tn", "47j")
key.set("n", "'te", "48j")
key.set("n", "'ti", "49j")

key.set("n", "'do", "50j")
key.set("n", "'da", "51j")
key.set("n", "'dr", "52j")
key.set("n", "'ds", "53j")
key.set("n", "'dt", "54j")
key.set("n", "'dd", "55j")
key.set("n", "'dh", "56j")
key.set("n", "'dn", "57j")
key.set("n", "'de", "58j")
key.set("n", "'di", "59j")

key.set("n", "'ho", "60j")
key.set("n", "'ha", "61j")
key.set("n", "'hr", "62j")
key.set("n", "'hs", "63j")
key.set("n", "'ht", "64j")
key.set("n", "'hd", "65j")
key.set("n", "'hh", "66j")
key.set("n", "'hn", "67j")
key.set("n", "'he", "68j")
key.set("n", "'hi", "69j")

key.set("n", "'no", "70j")
key.set("n", "'na", "71j")
key.set("n", "'nr", "72j")
key.set("n", "'ns", "73j")
key.set("n", "'nt", "74j")
key.set("n", "'nd", "75j")
key.set("n", "'nh", "76j")
key.set("n", "'nn", "77j")
key.set("n", "'ne", "78j")
key.set("n", "'ni", "79j")

key.set("n", "'eo", "80j")
key.set("n", "'ea", "81j")
key.set("n", "'er", "82j")
key.set("n", "'es", "83j")
key.set("n", "'et", "84j")
key.set("n", "'ed", "85j")
key.set("n", "'eh", "86j")
key.set("n", "'en", "87j")
key.set("n", "'ee", "88j")
key.set("n", "'ei", "89j")

key.set("n", "'io", "90j")
key.set("n", "'ia", "91j")
key.set("n", "'ir", "92j")
key.set("n", "'is", "93j")
key.set("n", "'it", "94j")
key.set("n", "'id", "95j")
key.set("n", "'ih", "96j")
key.set("n", "'in", "97j")
key.set("n", "'ie", "98j")
key.set("n", "'ii", "99j")
