local key = vim.keymap

key.set("n", "[a<leader>", "1k")
key.set("n", "[s<leader>", "2k")
key.set("n", "[d<leader>", "3k")
key.set("n", "[f<leader>", "4k")
key.set("n", "[g<leader>", "5k")
key.set("n", "[h<leader>", "6k")
key.set("n", "[j<leader>", "7k")
key.set("n", "[k<leader>", "8k")
key.set("n", "[l<leader>", "9k")

key.set("n", "[a;", "10k")
key.set("n", "[aa", "11k")
key.set("n", "[as", "12k")
key.set("n", "[ad", "13k")
key.set("n", "[af", "14k")
key.set("n", "[ag", "15k")
key.set("n", "[ah", "16k")
key.set("n", "[aj", "17k")
key.set("n", "[ak", "18k")
key.set("n", "[al", "19k")

key.set("n", "[s;", "20k")
key.set("n", "[sa", "21k")
key.set("n", "[ss", "22k")
key.set("n", "[sd", "23k")
key.set("n", "[sf", "24k")
key.set("n", "[sg", "25k")
key.set("n", "[sh", "26k")
key.set("n", "[sj", "27k")
key.set("n", "[sk", "28k")
key.set("n", "[sl", "29k")

key.set("n", "[d;", "30k")
key.set("n", "[da", "31k")
key.set("n", "[ds", "32k")
key.set("n", "[dd", "33k")
key.set("n", "[df", "34k")
key.set("n", "[dg", "35k")
key.set("n", "[dh", "36k")
key.set("n", "[dj", "37k")
key.set("n", "[dk", "38k")
key.set("n", "[dl", "39k")

key.set("n", "[f;", "40k")
key.set("n", "[fa", "41k")
key.set("n", "[fs", "42k")
key.set("n", "[fd", "43k")
key.set("n", "[ff", "44k")
key.set("n", "[fg", "45k")
key.set("n", "[fh", "46k")
key.set("n", "[fj", "47k")
key.set("n", "[fk", "48k")
key.set("n", "[fl", "49k")

key.set("n", "[g;", "50k")
key.set("n", "[ga", "51k")
key.set("n", "[gs", "52k")
key.set("n", "[gd", "53k")
key.set("n", "[gf", "54k")
key.set("n", "[gg", "55k")
key.set("n", "[gh", "56k")
key.set("n", "[gj", "57k")
key.set("n", "[gk", "58k")
key.set("n", "[gl", "59k")

key.set("n", "[h;", "60k")
key.set("n", "[ha", "61k")
key.set("n", "[hs", "62k")
key.set("n", "[hd", "63k")
key.set("n", "[hf", "64k")
key.set("n", "[hg", "65k")
key.set("n", "[hh", "66k")
key.set("n", "[hj", "67k")
key.set("n", "[hk", "68k")
key.set("n", "[hl", "69k")

key.set("n", "[j;", "70k")
key.set("n", "[ja", "71k")
key.set("n", "[js", "72k")
key.set("n", "[jd", "73k")
key.set("n", "[jf", "74k")
key.set("n", "[jg", "75k")
key.set("n", "[jh", "76k")
key.set("n", "[jj", "77k")
key.set("n", "[jk", "78k")
key.set("n", "[jl", "79k")

key.set("n", "[k;", "80k")
key.set("n", "[ka", "81k")
key.set("n", "[ks", "82k")
key.set("n", "[kd", "83k")
key.set("n", "[kf", "84k")
key.set("n", "[kg", "85k")
key.set("n", "[kh", "86k")
key.set("n", "[kj", "87k")
key.set("n", "[kk", "88k")
key.set("n", "[kl", "89k")

key.set("n", "[l;", "90k")
key.set("n", "[la", "91k")
key.set("n", "[ls", "92k")
key.set("n", "[ld", "93k")
key.set("n", "[lf", "94k")
key.set("n", "[lg", "95k")
key.set("n", "[lh", "96k")
key.set("n", "[lj", "97k")
key.set("n", "[lk", "98k")
key.set("n", "[ll", "99k")



key.set("n", "'a<leader>", "1j")
key.set("n", "'s<leader>", "2j")
key.set("n", "'d<leader>", "3j")
key.set("n", "'f<leader>", "4j")
key.set("n", "'g<leader>", "5j")
key.set("n", "'h<leader>", "6j")
key.set("n", "'j<leader>", "7j")
key.set("n", "'k<leader>", "8j")
key.set("n", "'l<leader>", "9j")

key.set("n", "'a;", "10j")
key.set("n", "'aa", "11j")
key.set("n", "'as", "12j")
key.set("n", "'ad", "13j")
key.set("n", "'af", "14j")
key.set("n", "'ag", "15j")
key.set("n", "'ah", "16j")
key.set("n", "'aj", "17j")
key.set("n", "'ak", "18j")
key.set("n", "'al", "19j")

key.set("n", "'s;", "20j")
key.set("n", "'sa", "21j")
key.set("n", "'ss", "22j")
key.set("n", "'sd", "23j")
key.set("n", "'sf", "24j")
key.set("n", "'sg", "25j")
key.set("n", "'sh", "26j")
key.set("n", "'sj", "27j")
key.set("n", "'sk", "28j")
key.set("n", "'sl", "29j")

key.set("n", "'d;", "30j")
key.set("n", "'da", "31j")
key.set("n", "'ds", "32j")
key.set("n", "'dd", "33j")
key.set("n", "'df", "34j")
key.set("n", "'dg", "35j")
key.set("n", "'dh", "36j")
key.set("n", "'dj", "37j")
key.set("n", "'dk", "38j")
key.set("n", "'dl", "39j")

key.set("n", "'f;", "40j")
key.set("n", "'fa", "41j")
key.set("n", "'fs", "42j")
key.set("n", "'fd", "43j")
key.set("n", "'ff", "44j")
key.set("n", "'fg", "45j")
key.set("n", "'fh", "46j")
key.set("n", "'fj", "47j")
key.set("n", "'fk", "48j")
key.set("n", "'fl", "49j")

key.set("n", "'g;", "50j")
key.set("n", "'ga", "51j")
key.set("n", "'gs", "52j")
key.set("n", "'gd", "53j")
key.set("n", "'gf", "54j")
key.set("n", "'gg", "55j")
key.set("n", "'gh", "56j")
key.set("n", "'gj", "57j")
key.set("n", "'gk", "58j")
key.set("n", "'gl", "59j")

key.set("n", "'h;", "60j")
key.set("n", "'ha", "61j")
key.set("n", "'hs", "62j")
key.set("n", "'hd", "63j")
key.set("n", "'hf", "64j")
key.set("n", "'hg", "65j")
key.set("n", "'hh", "66j")
key.set("n", "'hj", "67j")
key.set("n", "'hk", "68j")
key.set("n", "'hl", "69j")

key.set("n", "'j;", "70j")
key.set("n", "'ja", "71j")
key.set("n", "'js", "72j")
key.set("n", "'jd", "73j")
key.set("n", "'jf", "74j")
key.set("n", "'jg", "75j")
key.set("n", "'jh", "76j")
key.set("n", "'jj", "77j")
key.set("n", "'jk", "78j")
key.set("n", "'jl", "79j")

key.set("n", "'k;", "80j")
key.set("n", "'ka", "81j")
key.set("n", "'ks", "82j")
key.set("n", "'kd", "83j")
key.set("n", "'kf", "84j")
key.set("n", "'kg", "85j")
key.set("n", "'kh", "86j")
key.set("n", "'kj", "87j")
key.set("n", "'kk", "88j")
key.set("n", "'kl", "89j")

key.set("n", "'l;", "90j")
key.set("n", "'la", "91j")
key.set("n", "'ls", "92j")
key.set("n", "'ld", "93j")
key.set("n", "'lf", "94j")
key.set("n", "'lg", "95j")
key.set("n", "'lh", "96j")
key.set("n", "'lj", "97j")
key.set("n", "'lk", "98j")
key.set("n", "'ll", "99j")
